import Foundation

class QuestManager: ObservableObject {
    @Published var currentQuest: String = ""

    private let quests: [String] = [
        "Tanyakan arti dari nama panggilan seseorang yang baru kamu temui.",
        "Cari tahu makanan favoritnya dan tanyakan kenapa dia menyukainya.",
        "Tanyakan lagu yang sering dia dengarkan akhir-akhir ini dan dengarkan rekomendasinya.",
        "Minta dia mendeskripsikan dirinya dalam tiga kata.",
        "Tanyakan apakah dia lebih suka pagi atau malam, dan kenapa.",
        "Minta dia memilih antara bisa berbicara semua bahasa atau bermain semua alat musik, lalu tanyakan alasannya.",
        "Tanyakan tentang kebiasaan kecil yang selalu dia lakukan tanpa sadar.",
        "Minta dia menceritakan pengalaman paling spontan yang pernah dia lakukan.",
        "Ajak dia berbagi cerita tentang pengalaman paling memalukan dalam hidupnya.",
        "Tanyakan hewan peliharaan impiannya jika tidak ada batasan apa pun.",
        "Minta dia memilih antara kopi atau teh, lalu tanyakan bagaimana dia menikmatinya.",
        "Tanyakan hobi unik atau kebiasaan kecil yang membuatnya bahagia.",
        "Cari tahu film atau serial favoritnya sepanjang masa dan mengapa dia menyukainya.",
        "Tanyakan karakter film atau anime yang paling dia inginkan untuk diperankan.",
        "Minta dia memilih antara bekerja dalam tim atau sendiri, dan tanyakan alasannya.",
        "Tanyakan apakah dia lebih suka merencanakan sesuatu atau spontan dalam mengambil keputusan.",
        "Ajak dia berbagi tempat impian yang ingin dikunjungi dan alasan di baliknya.",
        "Minta dia memilih antara bisa terbang atau membaca pikiran, lalu tanyakan skenario terbaiknya.",
        "Cari tahu jika dia bisa jadi expert dalam satu bidang secara instan, apa yang dia pilih.",
        "Tanyakan satu keterampilan yang ingin dia pelajari dalam setahun ke depan.",
        "Minta dia memilih satu dunia film atau game yang ingin dia tinggali.",
        "Ajak dia berbagi pengalaman paling lucu yang pernah dia alami.",
        "Jika hanya bisa berbicara dalam judul lagu selama sehari, apa yang akan dia katakan?",
        "Pilih: Selalu berbicara dalam pantun atau selalu berbicara dengan nada lagu?",
        "Tanyakan menu makanan paling aneh yang pernah dia coba.",
        "Ceritakan tentang pengalaman kocak saat salah paham dengan seseorang.",
        "Jika bisa membuat peraturan aneh yang harus diikuti semua orang, apa itu?",
        "Minta dia berbagi kebiasaan kecil yang selalu dia lakukan tanpa sadar.",
        "Pilih: Bisa menggambar sempurna tapi hanya dengan tangan kiri, atau bisa menyanyi merdu tapi hanya lagu dangdut?",
        "Tanyakan pencapaian kecil yang paling dia banggakan.",
        "Jika bisa memberi nasihat ke diri sendiri di masa lalu, apa yang akan dia katakan?",
        "Apa satu kebiasaan yang ingin dia ubah atau tingkatkan tahun ini?",
        "Lebih suka jadi terkenal tapi sibuk atau hidup tenang tapi tidak terkenal?",
        "Jika bisa mengulang satu hari dalam hidupnya, hari apa yang akan dia pilih?",
        "Tanyakan siapa role model yang paling menginspirasinya.",
        "Jika bisa bekerja di pekerjaan impiannya besok, apa yang akan dia pilih?",
        "Minta dia memilih antara hidup tanpa media sosial atau tanpa musik.",
        "Tanyakan apa hal paling aneh yang dia bawa di dalam tasnya sekarang.",
        "Ceritakan kejadian random yang membuatnya tertawa baru-baru ini.",
        "Tanyakan apakah dia punya rutinitas pagi yang selalu dia lakukan.",
        "Minta dia memilih antara tinggal di kota besar atau pedesaan seumur hidup.",
        "Pilih: Bisa melihat masa depan 10 detik ke depan atau kembali ke masa lalu 10 menit?",
        "Jika bisa hidup di satu era sejarah mana pun, era apa yang dia pilih?",
        "Tanyakan jika dia bisa mendapatkan satu superpower, apa yang dia inginkan?",
        "Ceritakan tentang barang paling sentimental yang dia miliki.",
        "Jika harus membuat satu challenge sosial media, apa yang akan dia buat?",
        "Tanyakan apakah dia punya ritual unik sebelum melakukan sesuatu yang penting.",
        "Jika harus hidup di satu musim sepanjang tahun, musim apa yang dia pilih?",
        "Minta dia memilih antara selalu pakai outfit warna-warni atau hanya satu warna saja seumur hidup.",
        "Apa arti di balik tanggal lahirmu bagi keluargamu?",
        "Jika kamu bisa memilih nama sendiri, apakah kamu akan tetap menggunakan nama yang sama?",
        "Apa makanan atau minuman yang selalu bisa membuat harimu lebih baik?",
        "Apa pengalaman kecil yang membuatmu bangga dengan dirimu sendiri?",
        "Jika kamu harus menggambarkan kepribadianmu dengan satu emoji, emoji apa yang akan kamu pilih?",
        "Apa hal pertama yang kamu lakukan saat bangun tidur di pagi hari?",
        "Kamu lebih suka berbicara langsung atau melalui chat? Kenapa?",
        "Apa aplikasi yang paling sering kamu gunakan di ponselmu?",
        "Jika kamu bisa mengulang satu momen dalam hidupmu, momen apa yang akan kamu pilih?",
        "Apa satu kebiasaan yang menurut teman-temanmu unik dari dirimu?",
        "Jika kamu bisa hidup di era mana pun di masa lalu, era mana yang akan kamu pilih?",
        "Kamu lebih suka jalan-jalan di pantai atau di pegunungan? Kenapa?",
        "Apa kebiasaan kecil yang bisa langsung meningkatkan mood-mu?",
        "Jika kamu bisa makan hanya satu jenis makanan selama seminggu, makanan apa yang akan kamu pilih?",
        "Apa hal terkecil yang bisa membuatmu tersenyum?",
        "Lebih suka membaca buku atau menonton film? Kenapa?",
        "Jika kamu bisa bertemu dengan versi kecil dirimu di usia 10 tahun, apa yang akan kamu katakan padanya?",
        "Apa hal pertama yang menarik perhatianmu saat bertemu seseorang baru?",
        "Kalau harus mengganti pekerjaanmu sekarang dengan sesuatu yang sangat berbeda, pekerjaan apa yang akan kamu pilih?",
        "Jika kamu bisa belajar satu keahlian baru dalam semalam, keahlian apa yang akan kamu pilih?",
        "Apa sesuatu yang membuatmu merasa nyaman saat berada di lingkungan baru?",
        "Apa benda paling unik yang kamu miliki?",
        "Apa tempat terfavorit yang pernah kamu kunjungi, dan kenapa?",
        "Kamu lebih suka menghadiri acara besar atau kumpul kecil dengan teman-teman dekat?",
        "Apa sesuatu yang dulu kamu takutkan, tetapi sekarang kamu justru menyukainya?",
        "Jika kamu harus menghilangkan satu aplikasi dari ponselmu selamanya, aplikasi apa yang akan kamu hapus?",
        "Apa hal sederhana yang bisa membuat harimu jauh lebih baik?",
        "Punya ritual sebelum tidur? Kalau ada, apa itu?",
        "Kalau bisa menghabiskan sehari penuh tanpa batasan biaya, apa yang akan kamu lakukan?",
        "Apa hal paling menarik yang pernah kamu lihat atau dengar dari orang asing?",
        "Apa yang membuatmu merasa benar-benar dihargai oleh seseorang?",
        "Apa satu tantangan yang ingin kamu taklukkan dalam hidup?",
        "Lebih suka berbicara di depan umum atau mendengarkan diskusi orang lain?",
        "Jika bisa berteman dengan karakter dari film atau kartun, siapa yang akan kamu pilih?",
        "Apa kejadian lucu yang pernah kamu alami saat pertama kali bertemu seseorang?",
        "Apa barang yang selalu ada di dalam tas atau kantongmu?",
        "Apa sesuatu yang sering membuatmu penasaran, tetapi belum sempat kamu cari tahu?",
        "Kalau bisa menghabiskan satu hari melakukan apapun tanpa konsekuensi, apa yang akan kamu lakukan?",
        "Apa pertanyaan favoritmu untuk ditanyakan saat berkenalan dengan orang baru?",
        "Jika kamu harus memilih lagu tema untuk hidupmu, lagu apa yang akan kamu pilih?",
        "Kamu lebih suka bangun pagi atau begadang? Kenapa?",
        "Apa yang lebih penting bagimu: spontanitas atau perencanaan matang?",
        "Jika bisa memilih satu jenis transportasi untuk digunakan seumur hidup, apa yang akan kamu pilih?",
        "Apa hal terkecil yang bisa membuatmu merasa bahagia?",
        "Jika kamu bisa memiliki satu benda yang hanya ada di film atau game, apa yang akan kamu pilih?",
        "Apa sesuatu yang dulu kamu anggap remeh, tetapi sekarang kamu sadari sangat berharga?",
        "Bagaimana kamu biasanya memulai percakapan dengan orang baru?",
        "Apa satu pertanyaan yang ingin kamu tanyakan kepada banyak orang, tetapi jarang kamu tanyakan?"
        ]


    init() {
        shuffleQuest() // Langsung acak saat objek dibuat
    }

    func shuffleQuest() {
        currentQuest = quests.randomElement() ?? "Tidak ada quest tersedia"
    }
}
